### ISSUE TITLE
Dostosowanie do wymagań hurtowni

### ISSUE THREAD

**Issue by kubaporebski** [kubaporebski/P2#10]
Zgodnie z ustaleniami na zajęciach.

Procedurka składowana do nowego wymiaru - DimCategory

    insert into bdl.DimCategory
    select * from staging.DataTmp
    group by N1 ... itd.
    + ew. update

 Uporządkować tabelę faktów - DimFact
        - wyciągnąć N1 do innej kategorii
        - bedzie kategoria
        - w tabeli faktowej będzie id kategorii

    insert into FactData
    select * from staging.Data_tmp
    left join DimCategory...
    left join DimUnits...

**Comment by burbongw** [comment]
Całość wykonana w 4cea87e1a9dd98202ce51830cf52e02b091c5180
